/**
 * AUTO-GENERATED by tools/gen.ts from specs/openapi.json.
 * Do not edit directly — run `bun run gen` instead.
 */

export const TOCHKA_API_VERSION = "v1.90.3-stable" as const;
export const TOCHKA_API_TITLE = "Tochka.API" as const;
export const TOCHKA_BASE_URL_PROD = "https://enter.tochka.com/uapi/" as const;
export const TOCHKA_BASE_URL_SANDBOX = "https://enter.tochka.com/sandbox/v2/" as const;
