#!/usr/bin/env bun
import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { normalizePayGatewaySpec, readOpenApi } from "./openapi.js";
import { SPEC_TARGETS, type SpecTarget } from "./specs.js";

const OUT_DIR = resolve(import.meta.dir, "..", "packages", "tochka-sdk", "src", "_generated");
const META_FILE = resolve(OUT_DIR, "meta.ts");

function header(target: SpecTarget): string {
	return `/**
 * AUTO-GENERATED by tools/gen.ts from specs/${basename(target.path)}.
 * Do not edit directly — run \`bun run gen\` instead.
 */
`;
}

async function generateTypes(target: SpecTarget): Promise<{ path: string; content: string }> {
	console.log(`→ Generating ${target.label} types from ${target.path}`);
	const source =
		target.id === "pay-gateway"
			? (normalizePayGatewaySpec(await readOpenApi(target.path)) as unknown as Parameters<
					typeof openapiTS
				>[0])
			: pathToFileURL(target.path);
	const ast = await openapiTS(source, {
		alphabetize: true,
		exportType: true,
		rootTypes: true,
		immutable: false,
	});
	const body = astToString(ast);
	return { path: target.generatedPath, content: header(target) + body };
}

async function main() {
	const mainTarget = SPEC_TARGETS.find((target) => target.id === "tochka");
	if (!mainTarget) throw new Error("Missing Tochka API spec target");
	const spec = await readOpenApi(mainTarget.path);

	const prodServer = spec.servers.find((server) => /uapi/.test(server.url))?.url;
	const sandboxServer = spec.servers.find((server) => /sandbox/.test(server.url))?.url;
	if (!prodServer || !sandboxServer || prodServer === sandboxServer) {
		throw new Error("OpenAPI must declare distinct production and sandbox server URLs");
	}

	const meta = `${header(mainTarget)}
export const TOCHKA_API_VERSION = ${JSON.stringify(spec.info.version)} as const;
export const TOCHKA_API_TITLE = ${JSON.stringify(spec.info.title)} as const;
export const TOCHKA_BASE_URL_PROD = ${JSON.stringify(prodServer)} as const;
export const TOCHKA_BASE_URL_SANDBOX = ${JSON.stringify(sandboxServer)} as const;
`;
	const outputs = [
		...(await Promise.all(SPEC_TARGETS.map(generateTypes))),
		{ path: META_FILE, content: meta },
	];
	for (const output of outputs) {
		await mkdir(dirname(output.path), { recursive: true });
		await writeFile(output.path, output.content);
		console.log(`✓ Wrote ${output.path}`);
	}
}

await main();
