#!/usr/bin/env bun
import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { normalizePayGatewaySpec, readOpenApi } from "./openapi.js";
import { SPEC_TARGETS, type SpecTarget } from "./specs.js";

const OUT_DIR = resolve(import.meta.dir, "..", "packages", "tochka-sdk", "src", "_generated");
const META_FILE = resolve(OUT_DIR, "meta.ts");

function header(target: SpecTarget): string {
	return `/**
 * AUTO-GENERATED by tools/gen.ts from specs/${basename(target.path)}.
 * Do not edit directly — run \`bun run gen\` instead.
 */
`;
}

async function generateTypes(target: SpecTarget): Promise<void> {
	console.log(`→ Generating ${target.label} types from ${target.path}`);
	const source =
		target.id === "pay-gateway"
			? (normalizePayGatewaySpec(await readOpenApi(target.path)) as unknown as Parameters<
					typeof openapiTS
				>[0])
			: pathToFileURL(target.path);
	const ast = await openapiTS(source, {
		alphabetize: true,
		exportType: true,
		rootTypes: true,
		immutable: false,
	});
	const body = astToString(ast);
	await mkdir(dirname(target.generatedPath), { recursive: true });
	await writeFile(target.generatedPath, header(target) + body);
	console.log(`✓ Wrote ${target.generatedPath}`);
}

async function main() {
	await mkdir(OUT_DIR, { recursive: true });
	await Promise.all(SPEC_TARGETS.map(generateTypes));

	const mainTarget = SPEC_TARGETS.find((target) => target.id === "tochka");
	if (!mainTarget) throw new Error("Missing Tochka API spec target");
	const spec = await readOpenApi(mainTarget.path);

	const prodServer = spec.servers.find((server) => /uapi/.test(server.url))?.url;
	const sandboxServer = spec.servers.find((server) => /sandbox/.test(server.url))?.url;
	if (!prodServer || !sandboxServer) {
		throw new Error("OpenAPI must declare distinct production and sandbox server URLs");
	}

	const meta = `${header(mainTarget)}
export const TOCHKA_API_VERSION = ${JSON.stringify(spec.info.version)} as const;
export const TOCHKA_API_TITLE = ${JSON.stringify(spec.info.title)} as const;
export const TOCHKA_BASE_URL_PROD = ${JSON.stringify(prodServer)} as const;
export const TOCHKA_BASE_URL_SANDBOX = ${JSON.stringify(sandboxServer)} as const;
`;
	await writeFile(META_FILE, meta);
	console.log(`✓ Wrote ${META_FILE} (API version: ${spec.info.version})`);
}

await main();
